name: main

on:
  push:
    branches:
      - master
      - develop
      - 'feature/*'
    paths-ignore:
      - '**.md'
      - 'THANKS'
      - 'LICENSE'
      - 'releases/*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --non-interactive
      - run: yarn lint
      - run: yarn build
